name: Karate API Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: adopt

    - name: Install Karate
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>\${{ github.actor }}</username><password>\${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:install -DskipTests

    - name: Run /posts endpoint Test
      run: mvn test -Dtest=PostsTestRunner

    - name: Run /comments endpoint Test
      run: mvn test -Dtest=CommentsTestRunner

